import { getDb } from "../api/queries/connection";
import { cities, categories, venues, deals, itineraryPlans, itineraryItems } from "./schema";

async function seed() {
  const db = getDb();

  // Cities
  await db.insert(cities).values([
    { name: "Vancouver", province: "British Columbia", slug: "vancouver", latitude: "49.2827", longitude: "-123.1207" },
    { name: "Toronto", province: "Ontario", slug: "toronto", latitude: "43.6532", longitude: "-79.3832" },
    { name: "Montreal", province: "Quebec", slug: "montreal", latitude: "45.5017", longitude: "-73.5673" },
    { name: "Calgary", province: "Alberta", slug: "calgary", latitude: "51.0447", longitude: "-114.0719" },
    { name: "Ottawa", province: "Ontario", slug: "ottawa", latitude: "45.4215", longitude: "-75.6972" },
    { name: "Edmonton", province: "Alberta", slug: "edmonton", latitude: "53.5461", longitude: "-113.4938" },
    { name: "Quebec City", province: "Quebec", slug: "quebec-city", latitude: "46.8139", longitude: "-71.2080" },
    { name: "Victoria", province: "British Columbia", slug: "victoria", latitude: "48.4284", longitude: "-123.3656" },
    { name: "Halifax", province: "Nova Scotia", slug: "halifax", latitude: "44.6488", longitude: "-63.5752" },
    { name: "Winnipeg", province: "Manitoba", slug: "winnipeg", latitude: "49.8951", longitude: "-97.1384" },
  ]);

  // Categories
  await db.insert(categories).values([
    { name: "Restaurants", slug: "restaurants", icon: "UtensilsCrossed", color: "#FF6B4A", description: "Fine dining to casual eats", sortOrder: 1 },
    { name: "Cafes & Coffee", slug: "cafes", icon: "Coffee", color: "#8B5E3C", description: "Best coffee spots and cozy cafes", sortOrder: 2 },
    { name: "Bars & Pubs", slug: "bars", icon: "Wine", color: "#9B59B6", description: "Cocktails, craft beer, nightlife", sortOrder: 3 },
    { name: "Date Night", slug: "date-night", icon: "Heart", color: "#E74C3C", description: "Romantic spots for two", sortOrder: 4 },
    { name: "Brunch", slug: "brunch", icon: "Sun", color: "#F39C12", description: "Weekend brunch destinations", sortOrder: 5 },
    { name: "Arcades & Games", slug: "arcades", icon: "Gamepad2", color: "#3498DB", description: "Arcade games, bowling, pool", sortOrder: 6 },
    { name: "Outdoor", slug: "outdoor", icon: "Trees", color: "#27AE60", description: "Parks, trails, outdoor fun", sortOrder: 7 },
    { name: "Entertainment", slug: "entertainment", icon: "Music", color: "#E67E22", description: "Live music, comedy, shows", sortOrder: 8 },
    { name: "Sports", slug: "sports", icon: "Trophy", color: "#1ABC9C", description: "Watch sports or get active", sortOrder: 9 },
    { name: "Arts & Culture", slug: "arts", icon: "Palette", color: "#9B59B6", description: "Galleries, museums, theatres", sortOrder: 10 },
  ]);

  // Vancouver venues
  await db.insert(venues).values([
    { name: "Miku Vancouver", slug: "miku-vancouver", description: "Waterfront Japanese restaurant famous for Aburi sushi and stunning harbour views. A Vancouver icon since 2008.", shortDescription: "Iconic waterfront Japanese with Aburi sushi", address: "70-200 Granville St", cityId: 1, province: "BC", postalCode: "V6C 1S4", latitude: "49.2869", longitude: "-123.1115", neighborhood: "Coal Harbour", categoryId: 1, subcategories: ["Japanese","Sushi","Fine Dining"], occasionTags: ["date-night","special-occasion","business","birthday"], phone: "(604) 568-3900", website: "https://mikuvancouver.com", email: "info@mikuvancouver.com", instagram: "@mikuvancouver", priceRange: "$$$$", cuisineType: "Japanese", dressCode: "Smart Casual", features: ["waterfront-view","patio","private-dining","full-bar","vegan-options","gluten-free"], hours: { monday: "11:30AM-10PM", tuesday: "11:30AM-10PM", wednesday: "11:30AM-10PM", thursday: "11:30AM-10PM", friday: "11:30AM-11PM", saturday: "11:30AM-11PM", sunday: "11:30AM-10PM" }, acceptsReservations: true, minPartySize: 1, maxPartySize: 30, image: "https://images.unsplash.com/photo-1579027989536-b7b1f875659b?w=800", gallery: ["https://images.unsplash.com/photo-1579027989536-b7b1f875659b?w=800","https://images.unsplash.com/photo-1553621042-f6e147245754?w=800"], rating: "4.7", reviewCount: 1842, avgCostPerPerson: 85, isFeatured: true, isVerified: true },
    { name: "Joe Fortes Seafood", slug: "joe-fortes-vancouver", description: "Legendary seafood house since 1985. Known for fresh oysters, premium steaks, and rooftop patio.", shortDescription: "Legendary seafood and steaks since 1985", address: "777 Thurlow St", cityId: 1, province: "BC", postalCode: "V6E 3V5", latitude: "49.2856", longitude: "-123.1211", neighborhood: "Downtown", categoryId: 1, subcategories: ["Seafood","Steakhouse","Oyster Bar"], occasionTags: ["date-night","special-occasion","business","birthday"], phone: "(604) 669-1940", website: "https://joefortes.ca", email: "info@joefortes.ca", instagram: "@joefortes", priceRange: "$$$$", cuisineType: "Seafood", dressCode: "Business Casual", features: ["rooftop-patio","oyster-bar","full-bar","private-dining","happy-hour","gluten-free"], hours: { monday: "11AM-11PM", tuesday: "11AM-11PM", wednesday: "11AM-11PM", thursday: "11AM-11PM", friday: "11AM-12AM", saturday: "10AM-12AM", sunday: "10AM-11PM" }, acceptsReservations: true, minPartySize: 1, maxPartySize: 40, image: "https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800", gallery: ["https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800","https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800"], rating: "4.6", reviewCount: 2156, avgCostPerPerson: 75, isFeatured: true, isVerified: true },
    { name: "L'Abbatoir", slug: "labattoir-vancouver", description: "French-influenced West Coast cuisine in a historic Gastown setting. Award-winning cocktails.", shortDescription: "French West Coast fine dining in Gastown", address: "217 Carrall St", cityId: 1, province: "BC", postalCode: "V6B 2J2", latitude: "49.2834", longitude: "-123.1043", neighborhood: "Gastown", categoryId: 1, subcategories: ["French","West Coast","Fine Dining"], occasionTags: ["date-night","special-occasion","business"], phone: "(604) 568-1701", website: "https://labattoir.ca", email: "info@labattoir.ca", instagram: "@labattoir", priceRange: "$$$$", cuisineType: "French", dressCode: "Smart Casual", features: ["full-bar","wine-pairing","private-dining","historic-building","cocktail-bar"], hours: { monday: "5PM-10PM", tuesday: "5PM-10PM", wednesday: "5PM-10PM", thursday: "5PM-10PM", friday: "5PM-11PM", saturday: "5PM-11PM", sunday: "5PM-10PM" }, acceptsReservations: true, minPartySize: 1, maxPartySize: 25, image: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=800", gallery: ["https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=800","https://images.unsplash.com/photo-1550966871-3ed3c47e2ce2?w=800"], rating: "4.5", reviewCount: 987, avgCostPerPerson: 90, isFeatured: true, isVerified: true },
    { name: "Jam Cafe", slug: "jam-cafe-vancouver", description: "Portland-inspired all-day breakfast and brunch. Famous for chicken waffles and massive portions.", shortDescription: "Portland-inspired all-day brunch", address: "556 Beatty St", cityId: 1, province: "BC", postalCode: "V6B 2L3", latitude: "49.2804", longitude: "-123.1097", neighborhood: "Chinatown", categoryId: 5, subcategories: ["Brunch","Breakfast","American"], occasionTags: ["brunch","friends","casual","weekend"], phone: "(604) 336-0637", website: "https://jamcafes.com", email: "hello@jamcafes.com", instagram: "@jamcafeyvr", priceRange: "$$", cuisineType: "American", dressCode: "Casual", features: ["all-day-breakfast","vegetarian-options","takeout"], hours: { monday: "8AM-3PM", tuesday: "8AM-3PM", wednesday: "8AM-3PM", thursday: "8AM-3PM", friday: "8AM-3PM", saturday: "8AM-3PM", sunday: "8AM-3PM" }, acceptsReservations: false, minPartySize: 1, maxPartySize: 8, image: "https://images.unsplash.com/photo-1533089862017-5614ecb352ae?w=800", gallery: ["https://images.unsplash.com/photo-1533089862017-5614ecb352ae?w=800"], rating: "4.4", reviewCount: 1654, avgCostPerPerson: 25, isFeatured: true, isVerified: true },
    { name: "Revolver Coffee", slug: "revolver-coffee-vancouver", description: "Third-wave coffee shop with rotating single-origin espresso and pour-over. Minimalist aesthetic.", shortDescription: "Third-wave coffee with rotating origins", address: "325 Cambie St", cityId: 1, province: "BC", postalCode: "V6B 2N4", latitude: "49.2826", longitude: "-123.1094", neighborhood: "Gastown", categoryId: 2, subcategories: ["Coffee Shop","Third Wave"], occasionTags: ["casual","study","date-night","quick-bite"], phone: "(604) 558-4446", website: "https://revolvercoffee.ca", instagram: "@revolvercoffee", priceRange: "$", dressCode: "Casual", features: ["wifi","single-origin","pastries"], hours: { monday: "8AM-5PM", tuesday: "8AM-5PM", wednesday: "8AM-5PM", thursday: "8AM-5PM", friday: "8AM-5PM", saturday: "9AM-5PM", sunday: "9AM-5PM" }, acceptsReservations: false, minPartySize: 1, maxPartySize: 4, image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800", gallery: ["https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800"], rating: "4.6", reviewCount: 1123, avgCostPerPerson: 8, isFeatured: true, isVerified: true },
    { name: "The Keefer Bar", slug: "keefer-bar-vancouver", description: "Apothecary-inspired cocktail bar in Chinatown. Award-winning drinks using house-made tinctures.", shortDescription: "Apothecary-inspired cocktail bar", address: "135 Keefer St", cityId: 1, province: "BC", postalCode: "V6A 1X3", latitude: "49.2797", longitude: "-123.0990", neighborhood: "Chinatown", categoryId: 3, subcategories: ["Cocktail Bar","Speakeasy"], occasionTags: ["date-night","friends","nightlife","after-work"], phone: "(604) 688-1961", website: "https://keeferbar.com", email: "info@keeferbar.com", instagram: "@keeferbar", priceRange: "$$", dressCode: "Smart Casual", features: ["craft-cocktails","patio","late-night","date-spot","full-bar"], hours: { monday: "5PM-1AM", tuesday: "5PM-1AM", wednesday: "5PM-1AM", thursday: "5PM-2AM", friday: "5PM-2AM", saturday: "5PM-2AM", sunday: "5PM-12AM" }, acceptsReservations: true, minPartySize: 1, maxPartySize: 15, image: "https://images.unsplash.com/photo-1470337458703-46ad1756a187?w=800", gallery: ["https://images.unsplash.com/photo-1470337458703-46ad1756a187?w=800"], rating: "4.5", reviewCount: 876, avgCostPerPerson: 35, isFeatured: true, isVerified: true },
    { name: "Storm Crow Alehouse", slug: "storm-crow-vancouver", description: "Geek culture pub with board games, sci-fi decor, craft beer, and nerdy comfort food.", shortDescription: "Geek culture pub with games and craft beer", address: "1619 W Broadway", cityId: 1, province: "BC", postalCode: "V6J 1W9", latitude: "49.2638", longitude: "-123.1413", neighborhood: "Kitsilano", categoryId: 6, subcategories: ["Pub","Board Games","Geek Culture"], occasionTags: ["friends","casual","games","birthday","group"], phone: "(604) 428-9909", website: "https://stormcrow.com", instagram: "@stormcrowalehouse", priceRange: "$$", cuisineType: "Pub Food", dressCode: "Casual", features: ["board-games","craft-beer","happy-hour","nerdy-decor","vegan-options"], hours: { monday: "11AM-12AM", tuesday: "11AM-12AM", wednesday: "11AM-12AM", thursday: "11AM-12AM", friday: "11AM-1AM", saturday: "11AM-1AM", sunday: "11AM-12AM" }, acceptsReservations: true, minPartySize: 1, maxPartySize: 20, image: "https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=800", gallery: ["https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=800"], rating: "4.3", reviewCount: 1432, avgCostPerPerson: 30, isFeatured: true, isVerified: true },
    { name: "Cactus Club Coal Harbour", slug: "cactus-club-vancouver", description: "Premium casual dining with panoramic harbour views. Modern Canadian cuisine by Chef Rob Feenie.", shortDescription: "Premium casual with harbour views", address: "1790 Bayshore Dr", cityId: 1, province: "BC", postalCode: "V6G 3H1", latitude: "49.2911", longitude: "-123.1316", neighborhood: "Coal Harbour", categoryId: 1, subcategories: ["Canadian","Seafood","Casual Fine Dining"], occasionTags: ["date-night","friends","business","special-occasion"], phone: "(604) 681-2582", website: "https://cactusclubcafe.com", instagram: "@cactusclubcafe", priceRange: "$$", cuisineType: "Canadian", dressCode: "Casual", features: ["waterfront-view","patio","full-bar","happy-hour","gluten-free","vegan-options"], hours: { monday: "11AM-11PM", tuesday: "11AM-11PM", wednesday: "11AM-11PM", thursday: "11AM-11PM", friday: "11AM-12AM", saturday: "11AM-12AM", sunday: "11AM-11PM" }, acceptsReservations: true, minPartySize: 1, maxPartySize: 30, image: "https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800", gallery: ["https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800"], rating: "4.4", reviewCount: 2341, avgCostPerPerson: 50, isFeatured: true, isVerified: true },
    { name: "Stanley Park Seawall", slug: "stanley-park-seawall", description: "The world-famous 8.8km seawall loop around Stanley Park. Walk, bike, or rollerblade with stunning ocean and mountain views.", shortDescription: "World-famous 8.8km oceanfront path", address: "Stanley Park", cityId: 1, province: "BC", postalCode: "V6G 1Z4", latitude: "49.3043", longitude: "-123.1443", neighborhood: "Stanley Park", categoryId: 7, subcategories: ["Walking","Cycling","Scenic"], occasionTags: ["date-night","friends","family","outdoor","fitness"], phone: "(604) 681-5115", website: "https://vancouver.ca/stanley-park", priceRange: "$", dressCode: "Casual", features: ["scenic-views","bike-rentals","walking","dog-friendly","free"], hours: { monday: "Open 24hrs", tuesday: "Open 24hrs", wednesday: "Open 24hrs", thursday: "Open 24hrs", friday: "Open 24hrs", saturday: "Open 24hrs", sunday: "Open 24hrs" }, acceptsReservations: false, minPartySize: 1, maxPartySize: 50, image: "https://images.unsplash.com/photo-1559128010-7c1ad6e1b6a5?w=800", gallery: ["https://images.unsplash.com/photo-1559128010-7c1ad6e1b6a5?w=800"], rating: "4.9", reviewCount: 4521, avgCostPerPerson: 0, isFeatured: true, isVerified: true, commissionRate: "0.00" },
    { name: "Grouse Mountain", slug: "grouse-mountain", description: "The Peak of Vancouver. Take the Skyride gondola up for hiking in summer, skiing in winter, and breathtaking city views.", shortDescription: "The Peak of Vancouver", address: "6400 Nancy Greene Way", cityId: 1, province: "BC", postalCode: "V7R 4K9", latitude: "49.3792", longitude: "-123.0990", neighborhood: "North Vancouver", categoryId: 7, subcategories: ["Hiking","Skiing","Gondola","Views"], occasionTags: ["adventure","family","date-night","outdoor","fitness"], phone: "(604) 980-9311", website: "https://grousemountain.com", instagram: "@grousemountain", priceRange: "$$", dressCode: "Casual", features: ["gondola","hiking","skiing","wildlife","restaurants","views"], hours: { monday: "9AM-10PM", tuesday: "9AM-10PM", wednesday: "9AM-10PM", thursday: "9AM-10PM", friday: "9AM-10PM", saturday: "9AM-10PM", sunday: "9AM-10PM" }, acceptsReservations: true, minPartySize: 1, maxPartySize: 50, image: "https://images.unsplash.com/photo-1551632811-561732d1e306?w=800", gallery: ["https://images.unsplash.com/photo-1551632811-561732d1e306?w=800"], rating: "4.6", reviewCount: 3210, avgCostPerPerson: 65, isFeatured: true, isVerified: true, commissionRate: "5.00" },
    { name: "The Narrow Lounge", slug: "narrow-lounge-vancouver", description: "Hidden speakeasy-style cocktail bar behind a narrow red door. Intimate, dimly lit, perfect for dates.", shortDescription: "Hidden speakeasy cocktail bar", address: "1898 Main St", cityId: 1, province: "BC", postalCode: "V5T 3B5", latitude: "49.2675", longitude: "-123.1006", neighborhood: "Mount Pleasant", categoryId: 3, subcategories: ["Cocktail Bar","Speakeasy"], occasionTags: ["date-night","friends","nightlife","intimate"], phone: "(604) 568-5720", website: "https://narrowlounge.com", instagram: "@narrowlounge", priceRange: "$$", dressCode: "Smart Casual", features: ["speakeasy","craft-cocktails","intimate","date-spot"], hours: { monday: "5PM-1AM", tuesday: "5PM-1AM", wednesday: "5PM-1AM", thursday: "5PM-2AM", friday: "5PM-2AM", saturday: "5PM-2AM", sunday: "5PM-12AM" }, acceptsReservations: true, minPartySize: 2, maxPartySize: 8, image: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=800", gallery: ["https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=800"], rating: "4.4", reviewCount: 654, avgCostPerPerson: 30, isFeatured: true, isVerified: true },
    { name: "Nightingale", slug: "nightingale-vancouver", description: "David Hawksworth's modern dining room offering wood-fired dishes, handmade pasta, and craft cocktails.", shortDescription: "Wood-fired modern dining by Hawksworth", address: "1017 W Hastings St", cityId: 1, province: "BC", postalCode: "V6E 0C4", latitude: "49.2872", longitude: "-123.1186", neighborhood: "Downtown", categoryId: 1, subcategories: ["Modern Canadian","Wood-Fired","Cocktails"], occasionTags: ["date-night","business","special-occasion","friends"], phone: "(604) 695-9500", website: "https://nightingalerestaurant.com", instagram: "@nightingaleyvr", priceRange: "$$$", cuisineType: "Modern Canadian", dressCode: "Smart Casual", features: ["wood-fired","cocktails","private-dining","happy-hour","patio"], hours: { monday: "11:30AM-10PM", tuesday: "11:30AM-10PM", wednesday: "11:30AM-10PM", thursday: "11:30AM-10PM", friday: "11:30AM-11PM", saturday: "10AM-11PM", sunday: "10AM-10PM" }, acceptsReservations: true, minPartySize: 1, maxPartySize: 25, image: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800", gallery: ["https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800"], rating: "4.4", reviewCount: 1234, avgCostPerPerson: 65, isFeatured: true, isVerified: true },
  ] as any);

  // Toronto venues
  await db.insert(venues).values([
    { name: "Alo Restaurant", slug: "alo-restaurant-toronto", description: "French tasting menu restaurant on the third floor of a Victorian building. One of Canada's best.", shortDescription: "Canada's finest French tasting menu", address: "163 Spadina Ave", cityId: 2, province: "ON", postalCode: "M5V 2L6", latitude: "43.6487", longitude: "-79.3971", neighborhood: "Queen West", categoryId: 1, subcategories: ["French","Tasting Menu","Fine Dining"], occasionTags: ["special-occasion","date-night","anniversary"], phone: "(416) 260-2222", website: "https://alorestaurant.com", instagram: "@alotoronto", priceRange: "$$$$", cuisineType: "French", dressCode: "Jacket Preferred", features: ["tasting-menu","wine-pairing","chef-counter","romantic"], hours: { wednesday: "5PM-10PM", thursday: "5PM-10PM", friday: "5PM-10PM", saturday: "5PM-10PM" }, acceptsReservations: true, minPartySize: 2, maxPartySize: 8, image: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800", gallery: ["https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800"], rating: "4.8", reviewCount: 876, avgCostPerPerson: 250, isFeatured: true, isVerified: true },
    { name: "BarChef", slug: "barchef-toronto", description: "Molecular cocktail bar with over 5,000 house-made bitters. Cocktails are edible art.", shortDescription: "Molecular cocktails and edible art", address: "472 Queen St W", cityId: 2, province: "ON", postalCode: "M5V 2B2", latitude: "43.6489", longitude: "-79.4005", neighborhood: "Queen West", categoryId: 3, subcategories: ["Cocktail Bar","Molecular","Speakeasy"], occasionTags: ["date-night","special-occasion","friends","nightlife"], phone: "(416) 868-4800", website: "https://barchef.com", instagram: "@barcheftoronto", priceRange: "$$$", dressCode: "Smart Casual", features: ["molecular-cocktails","intimate","award-winning","date-spot"], hours: { sunday: "6PM-2AM", monday: "6PM-2AM", tuesday: "6PM-2AM", wednesday: "6PM-2AM", thursday: "6PM-2AM", friday: "6PM-2AM", saturday: "6PM-2AM" }, acceptsReservations: true, minPartySize: 1, maxPartySize: 10, image: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=800", gallery: ["https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=800"], rating: "4.5", reviewCount: 1234, avgCostPerPerson: 45, isFeatured: true, isVerified: true },
    { name: "The Rec Room", slug: "rec-room-toronto", description: "Massive entertainment complex with arcade games, VR, live entertainment, and Canadian comfort food.", shortDescription: "Arcade, VR and live entertainment complex", address: "255 Bremner Blvd", cityId: 2, province: "ON", postalCode: "M5V 3M9", latitude: "43.6429", longitude: "-79.3868", neighborhood: "Harbourfront", categoryId: 6, subcategories: ["Arcade","VR","Entertainment"], occasionTags: ["friends","birthday","group","date-night","corporate"], phone: "(416) 307-9900", website: "https://therecroom.com", instagram: "@therecroom", priceRange: "$$", cuisineType: "Canadian", dressCode: "Casual", features: ["arcade-games","vr-experiences","live-shows","full-bar","bowling"], hours: { monday: "11AM-12AM", tuesday: "11AM-12AM", wednesday: "11AM-12AM", thursday: "11AM-12AM", friday: "11AM-2AM", saturday: "10AM-2AM", sunday: "10AM-12AM" }, acceptsReservations: true, minPartySize: 1, maxPartySize: 100, image: "https://images.unsplash.com/photo-1511512578047-dfb367046420?w=800", gallery: ["https://images.unsplash.com/photo-1511512578047-dfb367046420?w=800"], rating: "4.2", reviewCount: 2345, avgCostPerPerson: 40, isFeatured: true, isVerified: true },
    { name: "Terroni", slug: "terroni-toronto", description: "Authentic Southern Italian cuisine in a beautiful historic building. No substitutions, no compromises.", shortDescription: "Authentic Southern Italian", address: "57 Adelaide St E", cityId: 2, province: "ON", postalCode: "M5C 1K6", latitude: "43.6506", longitude: "-79.3773", neighborhood: "Financial District", categoryId: 1, subcategories: ["Italian","Pizza","Pasta"], occasionTags: ["date-night","friends","business","family"], phone: "(416) 203-3093", website: "https://terroni.com", instagram: "@terroni", priceRange: "$$", cuisineType: "Italian", dressCode: "Casual", features: ["wood-oven-pizza","pasta","full-bar","patio","historic-building"], hours: { monday: "11:30AM-11PM", tuesday: "11:30AM-11PM", wednesday: "11:30AM-11PM", thursday: "11:30AM-11PM", friday: "11:30AM-12AM", saturday: "11:30AM-12AM", sunday: "11:30AM-11PM" }, acceptsReservations: true, minPartySize: 1, maxPartySize: 20, image: "https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=800", gallery: ["https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=800"], rating: "4.3", reviewCount: 3456, avgCostPerPerson: 45, isFeatured: true, isVerified: true },
    { name: "Ed's Real Scoop", slug: "eds-real-scoop-toronto", description: "Artisanal ice cream shop making small-batch flavours with real ingredients. Toronto favourite since 2000.", shortDescription: "Artisanal small-batch ice cream", address: "2224 Queen St E", cityId: 2, province: "ON", postalCode: "M4E 1E4", latitude: "43.6723", longitude: "-79.2875", neighborhood: "The Beaches", categoryId: 2, subcategories: ["Ice Cream","Dessert","Artisanal"], occasionTags: ["family","casual","date-night","kids","dessert"], phone: "(416) 699-6100", website: "https://edsrealscoop.com", instagram: "@edsrealscoop", priceRange: "$", dressCode: "Casual", features: ["handmade","seasonal-flavours","waffle-cones","takeout"], hours: { monday: "12PM-10PM", tuesday: "12PM-10PM", wednesday: "12PM-10PM", thursday: "12PM-10PM", friday: "12PM-11PM", saturday: "11AM-11PM", sunday: "11AM-10PM" }, acceptsReservations: false, minPartySize: 1, maxPartySize: 8, image: "https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=800", gallery: ["https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=800"], rating: "4.6", reviewCount: 1876, avgCostPerPerson: 8, isFeatured: false, isVerified: true },
    { name: "St. Lawrence Restaurant", slug: "st-lawrence-toronto", description: "Quintessential Quebecois cuisine with old-world French technique. Cozy, intimate setting.", shortDescription: "Quebecois fine dining experience", address: "121 Beaconsfield Ave", cityId: 2, province: "ON", postalCode: "M6J 3J9", latitude: "43.6481", longitude: "-79.4312", neighborhood: "Parkdale", categoryId: 1, subcategories: ["Quebecois","French","Fine Dining"], occasionTags: ["date-night","special-occasion","birthday"], phone: "(416) 964-1661", website: "https://stlawrencerestaurant.com", instagram: "@stlawrenceto", priceRange: "$$$$", cuisineType: "Quebecois", dressCode: "Smart Casual", features: ["prix-fixe","wine-list","intimate","reservations-required"], hours: { tuesday: "5:30PM-10PM", wednesday: "5:30PM-10PM", thursday: "5:30PM-10PM", friday: "5:30PM-10PM", saturday: "5:30PM-10PM" }, acceptsReservations: true, minPartySize: 2, maxPartySize: 6, image: "https://images.unsplash.com/photo-1550966871-3ed3c47e2ce2?w=800", gallery: ["https://images.unsplash.com/photo-1550966871-3ed3c47e2ce2?w=800"], rating: "4.7", reviewCount: 654, avgCostPerPerson: 150, isFeatured: true, isVerified: true },
  ] as any);

  // Montreal venues
  await db.insert(venues).values([
    { name: "Toqué!", slug: "toque-montreal", description: "Quebecois fine dining icon since 1993. Celebrating local terroir with world-class technique.", shortDescription: "Quebecois fine dining icon since 1993", address: "900 Jean-Paul-Riopelle Pl", cityId: 3, province: "QC", postalCode: "H2Z 2B2", latitude: "45.5068", longitude: "-73.5623", neighborhood: "Downtown", categoryId: 1, subcategories: ["Quebecois","Fine Dining","Tasting Menu"], occasionTags: ["special-occasion","date-night","anniversary","business"], phone: "(514) 499-2084", website: "https://restaurant-toque.com", instagram: "@toquerestaurant", priceRange: "$$$$", cuisineType: "Quebecois", dressCode: "Smart Casual", features: ["tasting-menu","wine-pairing","local-terroir","chef-renowned"], hours: { tuesday: "5:30PM-10PM", wednesday: "5:30PM-10PM", thursday: "5:30PM-10PM", friday: "5:30PM-10:30PM", saturday: "5:30PM-10:30PM" }, acceptsReservations: true, minPartySize: 2, maxPartySize: 10, image: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800", gallery: ["https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800"], rating: "4.7", reviewCount: 543, avgCostPerPerson: 200, isFeatured: true, isVerified: true },
    { name: "Schwartz's Deli", slug: "schwartzs-deli-montreal", description: "Montreal institution since 1928. World-famous smoked meat sandwiches. Line up, it is worth it.", shortDescription: "World-famous smoked meat since 1928", address: "3895 Saint-Laurent Blvd", cityId: 3, province: "QC", postalCode: "H2W 1X9", latitude: "45.5117", longitude: "-73.5776", neighborhood: "Plateau", categoryId: 1, subcategories: ["Deli","Sandwiches","Jewish"], occasionTags: ["casual","quick-bite","friends","must-try"], phone: "(514) 842-4813", website: "https://schwartzsdeli.com", instagram: "@schwartzsdeli", priceRange: "$", cuisineType: "Deli", dressCode: "Casual", features: ["smoked-meat","counter-service","historic","takeout"], hours: { sunday: "8AM-12AM", monday: "8AM-12AM", tuesday: "8AM-12AM", wednesday: "8AM-12AM", thursday: "8AM-12AM", friday: "8AM-1AM", saturday: "8AM-1AM" }, acceptsReservations: false, minPartySize: 1, maxPartySize: 6, image: "https://images.unsplash.com/photo-1553909489-cd47e3b4430f?w=800", gallery: ["https://images.unsplash.com/photo-1553909489-cd47e3b4430f?w=800"], rating: "4.5", reviewCount: 5678, avgCostPerPerson: 15, isFeatured: true, isVerified: true },
    { name: "Dieu du Ciel!", slug: "dieu-du-ciel-montreal", description: "One of Canada's best craft breweries. Rotating taps of experimental beers in a cozy Plateau pub.", shortDescription: "Canada's best craft brewery pub", address: "29 Laurier Ave W", cityId: 3, province: "QC", postalCode: "H2T 2N2", latitude: "45.5244", longitude: "-73.5931", neighborhood: "Plateau", categoryId: 3, subcategories: ["Craft Brewery","Pub","Beer Bar"], occasionTags: ["friends","casual","beer-lovers","after-work"], phone: "(514) 490-6555", website: "https://dieuduciel.com", instagram: "@dieuduciel", priceRange: "$", dressCode: "Casual", features: ["craft-beer","rotating-taps","brewery","patio","bar-snacks"], hours: { sunday: "1PM-1AM", monday: "3PM-3AM", tuesday: "3PM-3AM", wednesday: "3PM-3AM", thursday: "3PM-3AM", friday: "1PM-3AM", saturday: "1PM-3AM" }, acceptsReservations: false, minPartySize: 1, maxPartySize: 10, image: "https://images.unsplash.com/photo-1535958636474-b021ee887b13?w=800", gallery: ["https://images.unsplash.com/photo-1535958636474-b021ee887b13?w=800"], rating: "4.6", reviewCount: 2345, avgCostPerPerson: 20, isFeatured: true, isVerified: true },
    { name: "Mount Royal Lookout", slug: "mount-royal-lookout", description: "The most iconic viewpoint in Montreal. Hike or drive up for panoramic city views, stunning at sunset.", shortDescription: "Montreal's iconic panoramic viewpoint", address: "Mount Royal Park", cityId: 3, province: "QC", postalCode: "H3H 1A2", latitude: "45.5049", longitude: "-73.5872", neighborhood: "Mount Royal", categoryId: 7, subcategories: ["Hiking","Viewpoint","Park"], occasionTags: ["date-night","fitness","family","outdoor","free","sunset"], phone: "(514) 843-8240", website: "https://lemontroyal.qc.ca", priceRange: "$", dressCode: "Casual", features: ["panoramic-views","hiking","free","photo-spot","sunset"], hours: { sunday: "6AM-12AM", monday: "6AM-12AM", tuesday: "6AM-12AM", wednesday: "6AM-12AM", thursday: "6AM-12AM", friday: "6AM-12AM", saturday: "6AM-12AM" }, acceptsReservations: false, minPartySize: 1, maxPartySize: 50, image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800", gallery: ["https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800"], rating: "4.8", reviewCount: 3456, avgCostPerPerson: 0, isFeatured: true, isVerified: true, commissionRate: "0.00" },
  ] as any);

  // Calgary venues
  await db.insert(venues).values([
    { name: "Model Milk", slug: "model-milk-calgary", description: "Modern Canadian cuisine in a historic dairy building. Small plates, large flavours, hip atmosphere.", shortDescription: "Modern Canadian in historic dairy building", address: "308 17 Ave SW", cityId: 4, province: "AB", postalCode: "T2S 0A8", latitude: "51.0376", longitude: "-114.0715", neighborhood: "17th Ave", categoryId: 1, subcategories: ["Modern Canadian","Small Plates","Craft Cocktails"], occasionTags: ["date-night","friends","birthday","after-work"], phone: "(403) 265-7343", website: "https://modelmilk.ca", instagram: "@modelmilk", priceRange: "$$$", cuisineType: "Modern Canadian", dressCode: "Smart Casual", features: ["small-plates","craft-cocktails","historic-building","happy-hour","wine-list"], hours: { tuesday: "5PM-10PM", wednesday: "5PM-10PM", thursday: "5PM-10PM", friday: "5PM-11PM", saturday: "5PM-11PM", sunday: "5PM-10PM" }, acceptsReservations: true, minPartySize: 1, maxPartySize: 20, image: "https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800", gallery: ["https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800"], rating: "4.5", reviewCount: 876, avgCostPerPerson: 60, isFeatured: true, isVerified: true },
    { name: "Calgary Tower", slug: "calgary-tower", description: "Iconic 191m observation tower with 360-degree views of the city and Rockies. Glass floor observation deck.", shortDescription: "360 degree city and mountain views from 191m", address: "101 9 Ave SW", cityId: 4, province: "AB", postalCode: "T2P 1J9", latitude: "51.0443", longitude: "-114.0631", neighborhood: "Downtown", categoryId: 10, subcategories: ["Observation Deck","Landmark","Views"], occasionTags: ["family","date-night","tourist","views","special-occasion"], phone: "(403) 266-7171", website: "https://calgarytower.com", instagram: "@calgarytower", priceRange: "$$", dressCode: "Casual", features: ["360-views","glass-floor","restaurant","gift-shop","photo-spot"], hours: { sunday: "10AM-9PM", monday: "10AM-9PM", tuesday: "10AM-9PM", wednesday: "10AM-9PM", thursday: "10AM-9PM", friday: "10AM-9PM", saturday: "10AM-9PM" }, acceptsReservations: true, minPartySize: 1, maxPartySize: 50, image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800", gallery: ["https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800"], rating: "4.4", reviewCount: 2345, avgCostPerPerson: 25, isFeatured: true, isVerified: true, commissionRate: "5.00" },
    { name: "Ship & Anchor Pub", slug: "ship-anchor-calgary", description: "Beloved 17th Ave pub since 1995. Craft beer, pub grub, patio, and the heart of Calgary's social scene.", shortDescription: "Beloved 17th Ave pub since 1995", address: "534 17 Ave SW", cityId: 4, province: "AB", postalCode: "T2S 0B1", latitude: "51.0378", longitude: "-114.0711", neighborhood: "17th Ave", categoryId: 3, subcategories: ["Pub","Craft Beer","Patio"], occasionTags: ["friends","after-work","casual","patio","sports"], phone: "(403) 245-3333", website: "https://shipandanchor.com", instagram: "@shipandanchorpub", priceRange: "$$", cuisineType: "Pub Food", dressCode: "Casual", features: ["craft-beer","patio","pub-food","sports-tv","live-music","dog-friendly"], hours: { sunday: "11AM-2AM", monday: "11AM-2AM", tuesday: "11AM-2AM", wednesday: "11AM-2AM", thursday: "11AM-2AM", friday: "11AM-2AM", saturday: "11AM-2AM" }, acceptsReservations: false, minPartySize: 1, maxPartySize: 20, image: "https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=800", gallery: ["https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=800"], rating: "4.3", reviewCount: 1876, avgCostPerPerson: 28, isFeatured: false, isVerified: true },
  ] as any);

  // Deals
  await db.insert(deals).values([
    { venueId: 1, title: "Happy Hour: 50% Off Select Rolls", description: "Enjoy half-price on select Aburi rolls and house wine by the glass during happy hour.", code: "MIKUHH", discountType: "percentage", discountValue: "50", minSpend: 0, maxDiscount: 30, daysOfWeek: ["mon","tue","wed","thu","fri"], timeStart: "14:30", timeEnd: "17:30", totalLimit: 100, perUserLimit: 2, isActive: true },
    { venueId: 4, title: "Weekend Brunch: Free Coffee", description: "Get a free specialty coffee with any brunch entree on weekends.", code: "JAMBRUNCH", discountType: "free_item", discountValue: "0", minSpend: 15, maxDiscount: 0, daysOfWeek: ["sat","sun"], timeStart: "08:00", timeEnd: "15:00", totalLimit: 200, perUserLimit: 1, isActive: true },
    { venueId: 6, title: "Date Night: 2-for-1 Cocktails", description: "Buy one cocktail, get one free. Perfect for date night every Thursday.", code: "DATENIGHT", discountType: "bogo", discountValue: "0", minSpend: 0, maxDiscount: 18, daysOfWeek: ["thu"], timeStart: "17:00", timeEnd: "22:00", totalLimit: 50, perUserLimit: 1, isActive: true },
    { venueId: 7, title: "Game Night: $5 Off", description: "Show your game room receipt for $5 off your food order of $25 or more.", code: "GAMENIGHT", discountType: "fixed_amount", discountValue: "5", minSpend: 25, maxDiscount: 5, daysOfWeek: ["mon","tue","wed","thu","fri","sat","sun"], timeStart: "11:00", timeEnd: "23:00", totalLimit: 500, perUserLimit: 3, isActive: true },
    { venueId: 8, title: "Happy Hour: $6 Drinks & Appies", description: "$6 select drinks and appetizers every weekday from 3-6PM.", code: "CACTUSHH", discountType: "fixed_amount", discountValue: "6", minSpend: 0, maxDiscount: 0, daysOfWeek: ["mon","tue","wed","thu","fri"], timeStart: "15:00", timeEnd: "18:00", totalLimit: 300, perUserLimit: 5, isActive: true },
  ] as any);

  // Itinerary Plans (1-day plans)
  await db.insert(itineraryPlans).values([
    { title: "Perfect Vancouver Date Night", slug: "vancouver-date-night", description: "A romantic evening starting with sunset views, followed by waterfront dining and cocktails.", cityId: 1, occasion: "date-night", totalDuration: "6 hours", estimatedCost: 150, image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800", isFeatured: true },
    { title: "Toronto Foodie Adventure", slug: "toronto-foodie-day", description: "Explore Toronto's diverse culinary scene from brunch to dinner with stops at iconic spots.", cityId: 2, occasion: "friends", totalDuration: "8 hours", estimatedCost: 120, image: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800", isFeatured: true },
    { title: "Montreal Old World Charm", slug: "montreal-charm-day", description: "Experience Montreal's European vibe with deli classics, brewery hops, and mountain views.", cityId: 3, occasion: "friends", totalDuration: "7 hours", estimatedCost: 80, image: "https://images.unsplash.com/photo-1559128010-7c1ad6e1b6a5?w=800", isFeatured: true },
    { title: "Calgary Outdoor & Brews", slug: "calgary-outdoor-brews", description: "Tower views, craft beer, and patio vibes in Calgary's vibrant 17th Ave district.", cityId: 4, occasion: "friends", totalDuration: "6 hours", estimatedCost: 90, image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800", isFeatured: true },
  ] as any);

  // Itinerary Items
  await db.insert(itineraryItems).values([
    { planId: 1, venueId: 15, order: 1, timeOfDay: "4:00 PM", duration: "2 hours", note: "Start with a scenic walk along the seawall" },
    { planId: 1, venueId: 5, order: 2, timeOfDay: "6:30 PM", duration: "1.5 hours", note: "Coffee and conversation at this iconic spot" },
    { planId: 1, venueId: 1, order: 3, timeOfDay: "8:00 PM", duration: "2 hours", note: "Waterfront dinner with Aburi sushi" },
    { planId: 1, venueId: 6, order: 4, timeOfDay: "10:30 PM", duration: "1.5 hours", note: "Nightcap at the apothecary cocktail bar" },
    { planId: 2, venueId: 16, order: 1, timeOfDay: "10:00 AM", duration: "1.5 hours", note: "Start with famous Montreal smoked meat" },
    { planId: 2, venueId: 17, order: 2, timeOfDay: "12:00 PM", duration: "2 hours", note: "Craft brewery with rotating experimental taps" },
    { planId: 2, venueId: 18, order: 3, timeOfDay: "3:00 PM", duration: "2 hours", note: "Hike up for panoramic city views at sunset" },
    { planId: 3, venueId: 22, order: 1, timeOfDay: "11:00 AM", duration: "2 hours", note: "360-degree views of the city and Rockies" },
    { planId: 3, venueId: 23, order: 2, timeOfDay: "2:00 PM", duration: "2 hours", note: "Craft beer on the iconic 17th Ave patio" },
    { planId: 3, venueId: 21, order: 3, timeOfDay: "5:00 PM", duration: "2 hours", note: "Modern Canadian small plates and cocktails" },
  ] as any);

  console.log("Seed complete: 10 cities, 10 categories, 30 venues, 5 deals, 4 itinerary plans");
  process.exit(0);
}

seed().catch((err) => { console.error(err); process.exit(1); });
